### ISSUE TITLE
Unit tests failing in Windows

### ISSUE THREAD

**Issue by mcandre** [jshint/jshint#1049]
When I run `npm test` in Windows, I get some `TypeError`'s.

Trace:

    $ npm test

    > jshint@1.1.0 test c:\Documents and Settings\apenneba\Desktop\src\jshint
    > node ./make.js test

    Running tests...

    cli.js: ......FFFFFFFFFF
    TypeError: Cannot call method 'split' of undefined
        at loadIgnores (c:\Documents and Settings\apenneba\Desktop\src\jshint\src\cli\cli.js:186:24)
        at Object.exports.interpret (c:\Documents and Settings\apenneba\Desktop\src\jshint\src\cli\cli.js:419:13)
        at Object.exports.group.testRcFile (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:220:7)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap test which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testHomeRcFile (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:233:24)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap cwd which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testOneLevelRcLookup (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:259:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap cwd which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testTargetRelativeRcLookup (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:285:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap cwd which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testIgnoreFile (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:313:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap test which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testCollectFiles (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:348:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap cwd which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testGather (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:435:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap cwd which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testStatusCode (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:542:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap run which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testDrainCalledWhenThereIsBufferedOutput (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:577:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    TypeError: Attempted to wrap run which is already wrapped
        at Object.wrapMethod (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon.js:70:23)
        at Object.stub (c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\sinon\lib\sinon\stub.js:55:22)
        at Object.exports.group.testDrainNotCalledWhenThereIsNoBufferedOutput (c:\Documents
    and Settings\apenneba\Desktop\src\jshint\tests\cli.js:602:9)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:231:20
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:163:13
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:126:25
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:160:17
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\deps\async.js:458:34
        at Object.exports.group.setUp (c:\Documents and Settings\apenneba\Desktop\src\jshint\tests\cli.js:15:3)
        at c:\Documents and Settings\apenneba\Desktop\src\jshint\node_modules\nodeunit\lib\core.js:259:35

    core.js: .............................................
    envs.js: ................
    options.js: ...........................................................
    parser.js: .................................................................................................................................
    npm.js: .
    thirdparty.js: ......

    FAILURES: 10/717 assertions failed (5576ms)
    npm ERR! Test failed.  See above for more details.
    npm ERR! not ok code 0

System:

    $ specs node os
    Specs:

    specs 0.4
    https://github.com/mcandre/specs#readme

    npm --version
    1.2.17

    node --version
    v0.10.3

    systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    OS Name:                   Microsoft Windows XP Professional
    OS Version:                5.1.2600 Service Pack 3 Build 2600

**Comment by jugglinmike** [comment]
Thanks to gh-1991, we now run the project's automated tests in Windows after every commit to the `master` branch. The build is currently passing, and since there has been no activity on this issue in over two years, I think it's likely that the underlying issue has long since been resolved. Please let us know if there are still problems!
