### ISSUE TITLE
2.3.0 does not work with Rhino (out of range index)

### ISSUE THREAD

**Issue by ralfstx** [jshint/jshint#1422]
```
$ rhino jshint-rhino-2.3.0.js 
Exception in thread "main" java.lang.IllegalArgumentException: out of range index
	at org.mozilla.classfile.ClassFileWriter.add(ClassFileWriter.java:579)
	at org.mozilla.classfile.ClassFileWriter.addLoadConstant(ClassFileWriter.java:676)
	at org.mozilla.classfile.ClassFileWriter.addPush(ClassFileWriter.java:929)
	at org.mozilla.javascript.optimizer.Codegen.pushNumberAsObject(Codegen.java:1087)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2238)
	at org.mozilla.javascript.optimizer.BodyCodegen.visitArrayLiteral(Codegen.java:3085)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2318)
	at org.mozilla.javascript.optimizer.BodyCodegen.visitSetProp(Codegen.java:5026)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2592)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:2033)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1858)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(Codegen.java:1289)
	at org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:306)
	at org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:166)
	at org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:75)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2377)
	at org.mozilla.javascript.Context.compileString(Context.java:1335)
	at org.mozilla.javascript.Context.compileString(Context.java:1324)
	at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:599)
	at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:564)
	at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:535)
	at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:178)
	at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:102)
	at org.mozilla.javascript.Context.call(Context.java:489)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
	at org.mozilla.javascript.tools.shell.Main.exec(Main.java:160)
	at org.mozilla.javascript.tools.shell.Main.main(Main.java:138)
```

**Comment by lukeapage** [comment]
can anyone verify this is fixed?
