### ISSUE TITLE
2.5.6 breaks for in loops with switch

### ISSUE THREAD

**Issue by laurens** [jshint/jshint#1920]
Version 2.5.6 of jshint breaks with `for…in` loops that contain a `switch`:

`````
for (var key in objects) {
  if (!objects.hasOwnProperty(key)) {
    switch (key) {
    case 'foo':
      if (true) {
        hey();
      }
      break;
    case 'bar':
      if (true) {
        hey();
      }
    }
  }
}

````


This will result in the following error:

`````
TypeError: Cannot read property 'type' of undefined
    at Object.oldScope [as fud] (/Users/pnch/github/jshint/src/jshint.js:3734:38)
    at expression (/Users/pnch/github/jshint/src/jshint.js:1045:32)
    at statement (/Users/pnch/github/jshint/src/jshint.js:1730:9)
    at statements (/Users/pnch/github/jshint/src/jshint.js:1773:16)
    at block (/Users/pnch/github/jshint/src/jshint.js:1899:13)
    at Object.blockstmt.labelled [as fud] (/Users/pnch/github/jshint/src/jshint.js:4075:11)
    at expression (/Users/pnch/github/jshint/src/jshint.js:1045:32)
    at statement (/Users/pnch/github/jshint/src/jshint.js:1730:9)
    at statements (/Users/pnch/github/jshint/src/jshint.js:1773:16)
    at itself (/Users/pnch/github/jshint/src/jshint.js:5001:9)
````

**Comment by laurens** [comment]
Thx, @lukeapage
