### ISSUE TITLE
failed to install jshint on windows 7 x64, what's wrong?

### ISSUE THREAD

**Issue by chapgaga** [jshint/jshint#1968]
the error message is as follows:
```
1151 verbose addNamed [ 'glob', '3.2.11' ]
1152 verbose addNamed [ '3.2.11', '3.2.11' ]
1153 silly lockFile 3fffafa6-glob-3-2-11 glob@3.2.11
1154 verbose lock glob@3.2.11 C:\Users\chapgaga\AppData\Roaming\npm-cache\3fffafa6-glob-3-2-11.lock
1155 silly lockFile 584a4a05-sigmund-1-0-0 sigmund@~1.0.0
1156 error error rolling back Error: ENOTEMPTY, rmdir 'C:\Program Files\nodejs\node_modules\jshint\node_modules\htmlparser2\test\Events'
1156 error error rolling back  jshint@2.5.10 { [Error: ENOTEMPTY, rmdir 'C:\Program Files\nodejs\node_modules\jshint\node_modules\htmlparser2\test\Events']
1156 error error rolling back   errno: 53,
1156 error error rolling back   code: 'ENOTEMPTY',
1156 error error rolling back   path: 'C:\\Program Files\\nodejs\\node_modules\\jshint\\node_modules\\htmlparser2\\test\\Events' }
1157 error Error: No compatible version found: date-now@'^0.1.4'
1157 error Valid install targets:
1157 error ["0.1.0","0.1.1","0.1.3","0.1.2","0.1.4","1.0.0","1.0.1"]
1157 error     at installTargetsError (C:\Users\chapgaga\AppData\Roaming\nvm\v0.8.17\node_modules\npm\lib\cache.js:564:10)
1157 error     at C:\Users\chapgaga\AppData\Roaming\nvm\v0.8.17\node_modules\npm\lib\cache.js:479:10
1157 error     at saved (C:\Users\chapgaga\AppData\Roaming\nvm\v0.8.17\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
1157 error     at C:\Users\chapgaga\AppData\Roaming\nvm\v0.8.17\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:218:7
1157 error     at Object.oncomplete (fs.js:297:15)
1158 error If you need help, you may report this log at:
1158 error     <http://github.com/isaacs/npm/issues>
1158 error or email it to:
1158 error     <npm-@googlegroups.com>
1159 error System Windows_NT 6.1.7600
1160 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jshint"
1161 error cwd E:\
1162 error node -v v0.8.17
1163 error npm -v 1.2.0
1164 verbose exit [ 1, true ]
```

**Comment by alFReD-NSH** [comment]
Update your npm, `npm update -g npm` that will fix this.
