### ISSUE TITLE
JSHint error when parsing a for in loop that contains an if statement that's missing parens

### ISSUE THREAD

**Issue by kzsh** [jshint/jshint#2250]
node version: v0.10.33
jshint version: jshint@2.6.3
Originally discovered with: jshint@2.5.10
identical error for both versions.

Code that triggered the error (note the missing parens on the `if` in the `for in`):

    var myObj = {};
    for(foo in this.bars) {
        if this.bars.hasOwnProperty(foo) {
            myObj[foo] = this.bars[foo];
        }
    }
Stack trace in v2.6.3:

    /usr/local/lib/node_modules/jshint/src/jshint.js:5432
            throw err;
                ^
    TypeError: Cannot read property 'type' of undefined
        at Object.oldScope [as fud] (/usr/local/lib/node_modules/jshint/src/jshint.js:3822:15)
        at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:897:32)
        at statement (/usr/local/lib/node_modules/jshint/src/jshint.js:1599:9)
        at statements (/usr/local/lib/node_modules/jshint/src/jshint.js:1642:16)
        at block (/usr/local/lib/node_modules/jshint/src/jshint.js:1761:13)
        at Object.blockstmt.labelled [as fud] (/usr/local/lib/node_modules/jshint/src/jshint.js:4177:11)
        at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:897:32)
        at statement (/usr/local/lib/node_modules/jshint/src/jshint.js:1599:9)
        at statements (/usr/local/lib/node_modules/jshint/src/jshint.js:1642:16)
        at block (/usr/local/lib/node_modules/jshint/src/jshint.js:1761:13)

In case it helps here's the stack trace in v2.5.10:

    /usr/local/lib/node_modules/jshint/src/jshint.js:5271
            throw err;
                ^
    TypeError: Cannot read property 'type' of undefined
        at Object.oldScope [as fud] (/usr/local/lib/node_modules/jshint/src/jshint.js:3741:15)
        at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:1057:32)
        at statement (/usr/local/lib/node_modules/jshint/src/jshint.js:1745:9)
        at statements (/usr/local/lib/node_modules/jshint/src/jshint.js:1788:16)
        at block (/usr/local/lib/node_modules/jshint/src/jshint.js:1907:13)
        at Object.blockstmt.labelled [as fud] (/usr/local/lib/node_modules/jshint/src/jshint.js:4096:11)
        at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:1057:32)
        at statement (/usr/local/lib/node_modules/jshint/src/jshint.js:1745:9)
        at statements (/usr/local/lib/node_modules/jshint/src/jshint.js:1788:16)
        at block (/usr/local/lib/node_modules/jshint/src/jshint.js:1907:13)

**Comment by lukeapage** [comment]
In the latest release this does not crash but warns `Expected '(' and instead saw 'this'`

Please let us know if you don't think it is fixed.
