### ISSUE TITLE
Error with `typeof`

### ISSUE THREAD

**Issue by jamen** [jshint/jshint#2613]
When doing the following,
```javascript
if (typeof)
```

We get the error:

```
/usr/local/lib/node_modules/jshint/src/jshint.js:5521
        throw err;
              ^
TypeError: Cannot read property 'identifier' of undefined
    at Object.nud (/usr/local/lib/node_modules/jshint/src/jshint.js:2396:10)
    at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:888:34)
    at Object.fud (/usr/local/lib/node_modules/jshint/src/jshint.js:3873:16)
    at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:885:32)
    at statement (/usr/local/lib/node_modules/jshint/src/jshint.js:1635:9)
    at statements (/usr/local/lib/node_modules/jshint/src/jshint.js:1678:16)
    at itself (/usr/local/lib/node_modules/jshint/src/jshint.js:5384:9)
    at lint (/usr/local/lib/node_modules/jshint/src/cli.js:487:8)
    at /usr/local/lib/node_modules/jshint/src/cli.js:638:7
    at Array.forEach (native)
```

To reproduce this, you can use Node's CLI.  Simply put `if (typeof)` in a file named `test.js`, then run that file with `jshint test.js`

**Comment by caitp** [comment]
Are you saying you want jshint to do a better job of reporting syntax errors in your code?  Which version of jshint are you seeing this in?

**Comment by nicolo-ribaudo** [comment]
I think @JamenMarz is saying that JSHint shouldn't crash.
If so, this should have been fixed by #2508

**Comment by JamenMarz** [comment]
I just installed JSHint from npm today.

**Comment by nicolo-ribaudo** [comment]
That PR will be included in the next JSHint release.

**Comment by JamenMarz** [comment]
Ah okay.  Good to know.  I supposed that resolves this issue then.

**Comment by jamen** [comment]
I'm still receiving this error.

**Comment by jamen** [comment]
Just to make sure.  I checked `linter-jshint`'s `node_modules` folder, and looked at `jshint`'s `pacjage.json` file:

```
{
  "name": "jshint",
  "version": "2.8.0",
```

**Comment by jamen** [comment]
I installed `jshint` with `npm install -g jshint` just now, and tested:

```javascript
if (typeof)
```

And it crashed, here is the stack trace:

```
$ jshint ~/tests/jshint/typeof.js
/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:5521
        throw err;
        ^

TypeError: Cannot read property 'identifier' of undefined
    at Object.nud (/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:2396:10)
    at expression (/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:888:34)
    at Object.fud (/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:3873:16)
    at expression (/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:885:32)
    at statement (/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:1635:9)
    at statements (/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:1678:16)
    at itself (/home/jamen/.npm-global/lib/node_modules/jshint/src/jshint.js:5384:9)
    at lint (/home/jamen/.npm-global/lib/node_modules/jshint/src/cli.js:487:8)
    at /home/jamen/.npm-global/lib/node_modules/jshint/src/cli.js:638:7
    at Array.forEach (native)
```

**Comment by jugglinmike** [comment]
This issue was resolved by gh-2508. That patch was merged after the release of JSHint 2.8.0, so the fix will be included in the next release of JSHint.

**Comment by jamen** [comment]
Thanks for the clarification @jugglinmike, I was just curious about what happened - because I've been having this issue for a while after I closed it, so I was a bit confused on whether it was actually patched or not.

**Comment by jugglinmike** [comment]
No problem!
