### ISSUE TITLE
Error when passed --exclude-path node_modules/

### ISSUE THREAD

**Issue by nfriedly** [jshint/jshint#2650]
I'm not sure if this is me doing it wrong, or a bug in jshint, or a bug in shell.js, but when I try to lint everything except my node_modules/ directory, I get an EISDIR error:

```bash
~/nodejs-wrapper (dev) $ jshint -v
jshint v2.8.0
~/nodejs-wrapper (dev) $ jshint --exclude-path node_modules/ **/*.js
shell.js: internal error
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:552:19)
    at Object.fs.readFileSync (fs.js:384:28)
    at /usr/local/lib/node_modules/jshint/node_modules/shelljs/src/cat.js:35:15
    at Array.forEach (native)
    at Object._cat (/usr/local/lib/node_modules/jshint/node_modules/shelljs/src/cat.js:31:9)
    at Object.cat (/usr/local/lib/node_modules/jshint/node_modules/shelljs/src/common.js:186:23)
    at loadIgnores (/usr/local/lib/node_modules/jshint/src/cli.js:200:28)
    at Object.exports.interpret (/usr/local/lib/node_modules/jshint/src/cli.js:741:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/jshint/bin/jshint:3:26)
```

If I switch to `jshint --exclude-path node_modules/**/*.js **/*.js`, then it runs... but it lints things in my node_modules/ folder.

Creating a `.jshintignore` file with `node_modules/` does work as expected, so that's what I'm doing for now. But I thought you guys might still be interested in hearing about this.

**Comment by jugglinmike** [comment]
Can you share what OS and shell you are using? And does removing the trailing slash from `--exclude-path node_modules/` have any effect?

**Comment by nfriedly** [comment]
OS X 10.10.5. I'm mainly using [fish](http://fishshell.com/) but I get the same behavior in bash:

```bash
bash-3.2$ jshint --exclude-path node_modules/ **/*.js
shell.js: internal error
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:552:19)
    at Object.fs.readFileSync (fs.js:384:28)
    at /usr/local/lib/node_modules/jshint/node_modules/shelljs/src/cat.js:35:15
    at Array.forEach (native)
    at Object._cat (/usr/local/lib/node_modules/jshint/node_modules/shelljs/src/cat.js:31:9)
    at Object.cat (/usr/local/lib/node_modules/jshint/node_modules/shelljs/src/common.js:186:23)
    at loadIgnores (/usr/local/lib/node_modules/jshint/src/cli.js:200:28)
    at Object.exports.interpret (/usr/local/lib/node_modules/jshint/src/cli.js:741:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/jshint/bin/jshint:3:26)
```

I should have clarified that `jshint --exclude-path node_modules/**/*.js **/*.js`  version actually chokes in fish, but it processes node_modules in bash:

```bash
~/nodejs-wrapper (dev) $ jshint --exclude-path node_modules/**/*.js **/*.js
Failed to execute process '/usr/local/bin/jshint'. Reason:
The total size of the argument and environment lists 299kB exceeds the operating system limit of 299kB.
Try running the command again with fewer arguments.
~/nodejs-wrapper (dev) $ bash
bash-3.2$ jshint --exclude-path node_modules/**/*.js **/*.js
node_modules/extend/index.js: line 3, col 5, Expected an identifier and instead saw 'undefined' (a reserved word).
node_modules/extend/index.js: line 40, col 87, Expected '===' and instead saw '=='.
node_modules/extend/index.js: line 47, col 19, Expected '!==' and instead saw '!='.
node_modules/extend/index.js: line 3, col 5, 'undefined' is defined but never used.

node_modules/mocha/index.js: line 2, col 3, Bad line breaking before '?'.

node_modules/mocha/mocha.js: line 5, col 1, Missing "use strict" statement.
node_modules/mocha/mocha.js: line 7, col 7, Comma warnings can be turned off with 'laxcomma'.
node_modules/mocha/mocha.js: line 6, col 33, Bad line breaking before ','
...
```

The trailing slash doesn't seem to make any difference:

```bash
bash-3.2$ jshint --exclude-path node_modules **/*.js
shell.js: internal error
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:552:19)
    at Object.fs.readFileSync (fs.js:384:28)
    at /usr/local/lib/node_modules/jshint/node_modules/shelljs/src/cat.js:35:15
    at Array.forEach (native)
    at Object._cat (/usr/local/lib/node_modules/jshint/node_modules/shelljs/src/cat.js:31:9)
    at Object.cat (/usr/local/lib/node_modules/jshint/node_modules/shelljs/src/common.js:186:23)
    at loadIgnores (/usr/local/lib/node_modules/jshint/src/cli.js:200:28)
    at Object.exports.interpret (/usr/local/lib/node_modules/jshint/src/cli.js:741:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/jshint/bin/jshint:3:26)
```

**Comment by jugglinmike** [comment]
I think you want `--exclude`, not `--exclude-path`:

```
$ jshint --help
Usage:
  jshint [OPTIONS] [ARGS]

Options: 
  -c, --config STRING    Custom configuration file
      --reporter STRING  Custom reporter (<PATH>|jslint|checkstyle|unix) 
      --prereq STRING    Comma-separate list of prerequisite (paths). E.g. 
                         files which includedefinitions of global variabls 
                         used throughout your project 
      --exclude STRING   Exclude files matching the given filename pattern 
                         (same as .jshintignore) 
      --exclude-path STRINGPass in a custom jshintignore file path
      --filename STRING  Pass in a filename when using STDIN to emulate config 
                         lookup for that file name 
      --verbose          Show message codes
      --show-non-errors  Show additional data generated by jshint
  -e, --extra-ext STRING Comma-separated list of file extensions to use 
                         (default is .js) 
      --extract [STRING] Extract inline scripts contained in HTML 
                         (auto|always|never, default to never)  (Default is never)
      --jslint-reporter  Use a jslint compatible reporter (DEPRECATED, use 
                         --reporter=jslint instead) 
      --checkstyle-reporter Use a CheckStyle compatible XML reporter 
                            (DEPRECATED, use --reporter=checkstyle 
                            instead) 
  -v, --version          Display the current version
  -h, --help             Display help and usage details
```

**Comment by nfriedly** [comment]
Aah, you're right, I misread http://jshint.com/docs/cli/. So it was my mistake. Thanks for the help!

**Comment by jugglinmike** [comment]
Sure thing!
