### ISSUE TITLE
jshint doesn't see SyntaxError about yield precedence

### ISSUE THREAD

**Issue by norlin** [jshint/jshint#2923]
jshint doesn't see SyntaxError about yield precedence
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

Example:
```javascript
'use strict';
/* jshint esnext:true */

function*x(){
    return 2 + yield 3;
}
```

```
/Users/norlin/Work/hola.org/test.js:5
    return 2 + yield 3;
               ^^^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

jshint v2.9.2
nodejs v4.4.3

**Comment by xderry** [comment]
ESLint detects this correctly: http://eslint.org/demo/

'use strict';
/* eslint-env es6 */

function*x(){
    return 2 + yield 3;
}

**Comment by jugglinmike** [comment]
Thanks for the report! You're right--JSHint is currently very wrong about its
interpretation of the `yield` expression. I was hoping to have a patch for you
last weekend, but the fix is more involved than I anticipated. Still nothing to
show for my efforts yet, but I'm on the case!
