### ISSUE TITLE
TypeError: obj.forEach is not a function

### ISSUE THREAD

**Issue by yigitozkavci** [jshint/jshint#2941]
Problem is within atom package linter-jshint, but I think the main issue is in the source file. Adding image and the call stack here.

```
Error: /Users/macbookpro/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5099
      obj.forEach(cb);
          ^
TypeError: obj.forEach is not a function
    at each (/Users/macbookpro/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5099:11)
    at itself (/Users/macbookpro/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5103:7)
    at lint (/Users/macbookpro/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:495:8)
    at Object.<anonymous> (/Users/macbookpro/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:634:9)
    at Socket.<anonymous> (/Users/macbookpro/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
    at ChildProcess.<anonymous> (/Users/macbookpro/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
![image](https://cloud.githubusercontent.com/assets/7188811/15941100/6c889fbe-2e87-11e6-9625-11957409d550.png)

**Comment by jugglinmike** [comment]
Can you share your JSHint configuration? I'm particularly interested in the value of the `predef` option.

**Comment by yigitozkavci** [comment]
Yes, you're right. My wrong config file: 
```
{
  "esversion": 6,
  "curly": true,
  "eqeqeq": true,
  "predef": true
}
```
By looking to docs again, `predef` option value should be an `array` in stead of `boolean`. Thanks, closing :)

**Comment by nicolo-ribaudo** [comment]
Anyway, I think JSHint should report E002 instead of crashing.
