### ISSUE TITLE
Module Declarations allowed in invalid positions

### ISSUE THREAD

**Issue by jugglinmike** [jshint/jshint#2975]
```js
// jshint esversion: 6, module: true
{
  import x from './m.js';
}
```

Expected: error (ImportDeclaration is not allowed outside of a ModuleItem)
Actual: no warning

**Comment by sstern6** [comment]
@jugglinmike I am very interested in creating a PR for this bug.  I am brand new to the code base and was wondering if you could point me in the direction of a folder or file that would be a good start?

Thanks

**Comment by jugglinmike** [comment]
Sure thing! Here are the relevant parts of the codebase:

- [Logic for `import` declarations](https://github.com/jshint/jshint/blob/3ef7a0395cea5ec963a51f69b55a404f3f8e4578/src/jshint.js#L4500)
- [Logic for `export` declarations](https://github.com/jshint/jshint/blob/3ef7a0395cea5ec963a51f69b55a404f3f8e4578/src/jshint.js#L4588)
- [Utility method to detect the global scope](https://github.com/jshint/jshint/blob/3ef7a0395cea5ec963a51f69b55a404f3f8e4578/src/scope-manager.js#L771-L777)

If you have any more questions, don't hesitate to ask.

**Comment by sstern6** [comment]
Thank you!  Ill get cranking and will probably have questions

**Comment by sstern6** [comment]
@jugglinmike having some issues setting up local env.  I followed the guides, ran `npm install`, then `bin/build`. finally `npm test` and I am getting 1 error from the cli.js.  Attaches is the output, any idea why this could be happeneing? I am on a mac FYI.

```
> jshint@2.9.2 pretest /Users/scottstern/Desktop/JSHINT/jshint
> jshint src && jscs src

No code style errors found.

> jshint@2.9.2 test /Users/scottstern/Desktop/JSHINT/jshint
> npm run test-node && npm run test-browser


> jshint@2.9.2 test-node /Users/scottstern/Desktop/JSHINT/jshint
> npm run test-unit && npm run test-cli && npm run test-regression


> jshint@2.9.2 test-unit /Users/scottstern/Desktop/JSHINT/jshint
> nodeunit tests/unit


core
✔ testCustomGlobals
✔ testUnusedDefinedGlobals
✔ testImplieds
✔ testExportedDefinedGlobals
✔ testGlobalVarDeclarations
✔ globalDeclarations
✔ multilineGlobalDeclarations
✔ testNewArray
✔ testNewNonNativeArray
✔ testNonNativeArray
✔ testNewObject
✔ testNewNonNativeObject
✔ testUndefinedAsParam
✔ newLineAfterDot
✔ noDelete
✔ switchFallThrough
✔ switchDefaultFirst
✔ testVoid
✔ functionScopedOptions
✔ jslintOptions
✔ jslintInverted
✔ jslintRenamed
✔ jslintSloppy
✔ jslintUnrecognized
✔ caseExpressions
✔ returnStatement
✔ argsInCatchReused
✔ testRawOnError
✔ yesEmptyStmt
✔ insideEval
✔ escapedEvil
✔ noExcOnTooManyUndefined
✔ defensiveSemicolon
✔ iife
✔ invalidOptions
✔ multilineArray
✔ testInvalidSource
✔ testConstructor
✔ missingRadix
✔ NumberNaN
✔ htmlEscapement
✔ testSparseArrays
✔ testReserved
✔ testES5Reserved
✔ testCatchBlocks
✔ testNumericParams
✔ testForIn
✔ testRegexArray
✔ testUndefinedAssignment
✔ testES6Modules
✔ testES6ModulesNamedExportsAffectUnused
✔ testConstRedeclaration
✔ test typeof in TDZ
✔ testConstModification
✔ class declaration export
✔ function declaration export
✔ classIsBlockScoped
✔ testES6ModulesNamedExportsAffectUndef
✔ testES6ModulesThroughExportDoNotAffectUnused
✔ testES6ModulesThroughExportDoNotAffectUndef
✔ testES6ModulesDefaultExportsAffectUnused
✔ testES6ModulesDefaultExportAssignmentExpr
✔ testES6ModulesNameSpaceImportsAffectUnused
✔ testES6TemplateLiterals
✔ testES6TaggedTemplateLiterals
✔ testES6TemplateLiteralsUnused
✔ testES6TaggedTemplateLiteralsUnused
✔ testES6TemplateLiteralsUndef
✔ testES6TaggedTemplateLiteralsUndef
✔ testES6TemplateLiteralMultiline
✔ testES6TemplateLiteralsAreNotDirectives
✔ testES6TemplateLiteralReturnValue
✔ testES6TemplateLiteralMultilineReturnValue
✔ testES6TaggedTemplateLiteralMultilineReturnValue
✔ testES6TemplateLiteralMultilineReturnValueWithFunctionCall
✔ testES6TaggedTemplateLiteralMultilineReturnValueWithFunctionCall
✔ testMultilineReturnValueStringLiteral
✔ testES6ExportStarFrom
✔ testPotentialVariableLeak
✔ testDefaultArguments
✔ testDuplicateParamNames
✔ testClonePassedObjects
✔ testMagicProtoVariable
✔ testColumnNumAfterNonStrictComparison
✔ testArrayPrototypeExtensions
✔ testIncorrectJsonDetection
✔ testEscapedReservedWords
✔ testUnnamedFuncStatement
✔ testUnCleanedForinifcheckneeded
✔ testPermitEvalAsKey
✔ beginningArraysAreNotJSON
✔ labelsOutOfScope
✔ labelThroughCatch
✔ labelDoesNotExistInGlobalScope
✔ labeledBreakWithoutLoop
✔ labeledContinueWithoutLoop
✔ unlabeledBreakWithoutLoop
✔ unlabeledContinueWithoutLoop
✔ labelsContinue
✔ catchWithNoParam
✔ tryWithoutCatch
✔ gh-1920
✔ duplicateProto
✔ gh-2761
✔ gh-2838
✔ destructuring in setter parameter

envs
✔ node
✔ typed
✔ es5
✔ phantom
✔ globals

module-api
✔ test for GH-1103
✔ identifiers

options
✔ shadow
✔ shadowouter
✔ shadowInline
✔ shadowEs6
✔ latedef
✔ latedefInline
✔ notypeof
✔ combination of latedef and undef
✔ undefwstrict
✔ implied and unused should respect hoisting
✔ testProtoAndIterator
✔ testCamelcase
✔ curly
✔ noempty
✔ noarg
✔ nonew
✔ shelljs
✔ asi
✔ safeasi
✔ missing semicolons not influenced by asi
✔ lastsemic
✔ expr
✔ undef
✔ undefToOpMethods
✔ undefDeleteStrict
✔ unused - basic
✔ unused - usedThroughShadowedDeclaration
✔ unused - unusedThroughShadowedDeclaration
✔ unused - hoisted
✔ unused - crossBlocks
✔ param overrides function name expression
✔ let can re-use function and class name
✔ unused with param destructuring
✔ unused data with options
✔ unused with global override
✔ unused overrides
✔ unused overrides esnext
✔ unused with latedef function
✔ undef in a function scope
✔ scripturl
✔ forin
✔ loopfunc
✔ boss
✔ eqnull
✔ supernew
✔ bitwise
✔ debug
✔ eqeqeq
✔ evil
✔ immed
✔ plusplus
✔ newcap
✔ sub
✔ strict
✔ strictEnvs
✔ strictNoise
✔ globalstrict
✔ laxbreak
✔ validthis
✔ strings
✔ quotes
✔ quotesInline
✔ quotesAndTemplateLiterals
✔ scope - basic
✔ scope - crossBlocks
✔ esnext
✔ mozAndEs6
✔ maxlen
✔ laxcomma
✔ browser
✔ unnecessarysemicolon
✔ blacklist
✔ maxstatements
✔ maxdepth
✔ maxparams
✔ maxcomplexity
✔ fnmetrics
✔ ignored
✔ unignored
✔ per-line undef / -W117
✔ freeze
✔ nonbsp
✔ nocomma
✔ enforceall
✔ removeglobal
✔ ignoreDelimiters
✔ esnextPredefs
✔ singleGroups - loneIdentifier
✔ singleGroups - neighborless
✔ singleGroups - bindingPower - singleExpr
✔ singleGroups - bindingPower - multiExpr
✔ singleGroups - multiExpr
✔ singleGroups - concatenation
✔ singleGroups - functionExpression
✔ singleGroups - generatorExpression
✔ singleGroups - arrowFunctions
✔ singleGroups - objectLiterals
✔ singleGroups - newLine
✔ singleGroups - lineNumber
✔ singleGroups - unary
✔ singleGroups - numberLiterals
✔ singleGroups - postfix
✔ singleGroups - destructuringAssign
✔ elision
✔ badInlineOptionValue
✔ futureHostile
✔ varstmt
✔ module - behavior
✔ module - declarationRestrictions
✔ module - newcap
✔ module - await
✔ esversion

parser
✔ unsafe
✔ other
✔ confusingOps
✔ division
✔ plusplus
✔ assignment
✔ relations
✔ options
✔ emptyDirectives
✔ jshint option comments single line
✔ jshint option comments single line, leading and trailing space
✔ jshint option comments multi line
✔ jshint option comments multi line, leading and trailing space
✔ jshint option comments multi line/option
✔ jshint option comments multi line/option, leading and trailing space
✔ shebang
✔ shebangImpliesNode
✔ numbers
✔ comments
✔ regexp
✔ testRegexRegressions
✔ strings
✔ badStrings
✔ ownProperty
✔ json - dflt
✔ json - deep
✔ json - errors
✔ json - semicolon
✔ comma
✔ gh-2587
✔ badAssignments
✔ withStatement
✔ blocks
✔ functionCharacterLocation
✔ exported
✔ testIdentifiers
✔ badIdentifiers
✔ regression for GH-878
✔ regression for GH-910
✔ testHtml
✔ destructuring var in function scope
✔ destructuring var as moz
✔ destructuring var as esnext
✔ destructuring var as es5
✔ destructuring var as legacy JS
✔ destructuring var errors
✔ destructuring const as moz
✔ destructuring const as esnext
✔ destructuring const as es5
✔ destructuring const as legacy JS
✔ destructuring const errors
✔ destructuring globals as moz
✔ destructuring globals as esnext
✔ destructuring globals as es5
✔ destructuring globals as legacy JS
✔ destructuring globals with syntax error
✔ destructuring assign of empty values as moz
✔ destructuring assign of empty values as esnext
✔ destructuring assign of empty values as es5
✔ destructuring assign of empty values as JS legacy
✔ destructuring assignment default values
✔ destructuring assignment of valid simple assignment targets
✔ non-identifier PropertyNames in object destructuring
✔ empty destructuring
✔ array element assignment inside array
✔ let statement as moz
✔ let statement as esnext
✔ let statement as es5
✔ let statement as legacy JS
✔ let statement out of scope as moz
✔ let statement out of scope as esnext
✔ let statement out of scope as es5
✔ let statement out of scope as legacy JS
✔ let statement in functions as moz
✔ let statement in functions as esnext
✔ let statement in functions as es5
✔ let statement in functions as legacy JS
✔ let statement not in scope as moz
✔ let statement not in scope as esnext
✔ let statement not in scope as es5
✔ let statement not in scope as legacy JS
✔ let statement in for loop as moz
✔ let statement in for loop as esnext
✔ let statement in for loop as es5
✔ let statement in for loop as legacy JS
✔ let statement in destructured for loop as moz
✔ let statement in destructured for loop as esnext
✔ let statement in destructured for loop as es5
✔ let statement in destructured for loop as legacy JS
✔ let statement (as seen in jetpack)
✔ let statement (as seen in jetpack) as esnext
✔ let statement (as seen in jetpack) as es5
✔ let statement (as seen in jetpack) as legacy JS
✔ let block and let expression
✔ let block and let expression as esnext
✔ let block and let expression as es5
✔ let block and let expression as legacy JS
✔ make sure let variables are not treated as globals
✔ make sure var variables can shadow let variables
✔ make sure let variables in the closure of functions shadow predefined globals
✔ make sure let variables in the closure of blocks shadow predefined globals
✔ make sure variables may shadow globals in functions after they are referenced
✔ test block scope redefines globals only outside of blocks
✔ test destructuring function as moz
✔ test destructuring function as esnext
✔ test destructuring function as es5
✔ test destructuring function as legacy JS
✔ destructuring function default values
✔ non var destructuring assignment statement
✔ invalid for each
✔ invalid for each as esnext
✔ invalid for each as ES5
✔ invalid for each as legacy JS
✔ esnext generator
✔ esnext generator as moz extension
✔ esnext generator as es5
✔ esnext generator as legacy JS
✔ esnext generator without yield
✔ esnext generator without yield and check turned off
✔ esnext generator with yield delegation, gh-1544
✔ mozilla generator
✔ mozilla generator as esnext
✔ yield statement within try-catch
✔ mozilla generator as es5
✔ mozilla generator as legacy JS
✔ array comprehension
✔ array comprehension unused and undefined
✔ gh-1856 mistakenly identified as array comprehension
✔ gh-1413 wrongly detected as array comprehension
✔ moz-style array comprehension
✔ array comprehension with for..of
✔ moz-style array comprehension with for..of
✔ array comprehension with unused variables
✔ moz-style array comprehension with unused variables
✔ moz-style array comprehension as esnext
✔ array comprehension as es5
✔ moz-style array comprehension as es5
✔ array comprehension as legacy JS
✔ moz-style array comprehension as legacy JS
✔ array comprehension with dest array at global scope
✔ moz-style array comprehension with dest array at global scope
✔ moz-style array comprehension with dest array at global scope as esnext
✔ array comprehension with dest array at global scope as es5
✔ moz-style array comprehension with dest array at global scope as es5
✔ array comprehension with dest array at global scope as JS legacy
✔ moz-style array comprehension with dest array at global scope as JS legacy
✔ array comprehension imbrication with dest array
✔ moz-style array comprehension imbrication with dest array
✔ moz-style array comprehension imbrication with dest array using for..of
✔ moz-style array comprehension imbrication with dest array as esnext
✔ array comprehension imbrication with dest array as es5
✔ moz-style array comprehension imbrication with dest array as es5
✔ array comprehension imbrication with dest array as legacy JS
✔ moz-style array comprehension imbrication with dest array as legacy JS
✔ no false positive array comprehension
✔ try catch filters
✔ try catch filters as esnext
✔ try catch filters as es5
✔ try catch filters as legacy JS
✔ function closure expression
✔ function closure expression as esnext
✔ function closure expression as es5
✔ function closure expression as legacy JS
✔ for of as esnext
✔ for of as es5
✔ for of as legacy JS
✔ array destructuring for of as esnext
✔ array destructuring for of as es5
✔ array destructuring for of as legacy JS
✔ object destructuring for of as esnext
✔ object destructuring for of as es5
✔ object destructuring for of as legacy JS
✔ try multi-catch for moz extensions
✔ try multi-catch as esnext
✔ try multi-catch as es5
✔ try multi-catch as legacy JS
✔ no let not directly within a block
✔ no const not directly within a block
✔ test: let declared directly within block
✔ test: let is directly within nested block
✔ regression test for crash from GH-964
✔ automatic comma insertion GH-950
✔ fat arrows support
✔ fat arrow nested function scoping
✔ default arguments in fat arrow functions
✔ expressions in place of arrow function parameters
✔ conciseMethods - basicSupport
✔ conciseMethods - getAndSet
✔ conciseMethods - getWithoutSet
✔ conciseMethods - nameIsNotLocalVar
✔ object short notation: basic
✔ object short notation: mixed
✔ object ComputedPropertyName
✔ spread & rest operator support
✔ parameter destructuring with rest
✔ test for GH-1010
✔ classes
✔ class and method naming
✔ computed class methods aren't duplicate
✔ class method this
✔ classNewcap
✔ classExpression
✔ functionReassignment
✔ functionNotOverwritten
✔ classExpressionThis
✔ classElementEmpty
✔ invalidClasses
✔ test for GH-1018
✔ test warnings for assignments in conditionals
✔ test for GH-1089
✔ test for GH-1105
✔ test for crash with invalid condition
✔ test 'yield' in compound expressions.
✔ test for GH-387
✔ test for line breaks with 'yield'
✔ unreachable - regression for GH-1227
✔ unreachable - break
✔ unreachable - continue
✔ unreachable - return
✔ unreachable - throw
✔ unreachable - braceless
✔ unreachable - nestedBraceless
✔ test for 'break' in switch case + curly braces
✔ test for 'break' in switch case in loop + curly braces
✔ allow expression with a comma in switch case condition
✔ ignoreDirective - should be a good option and only accept start, end or line as values
✔ ignoreDirective - should allow the linter to skip blocked-out lines to continue finding errors in the rest of the code
✔ ignoreDirective - should ignore lines that appear to end with multiline comment endings (GH-1691)
✔ ignoreDirective - should ignore lines that end with a multi-line comment (GH-1396)
✔ ignoreDirective - should ignore multi-line comments
✔ ignoreDirective - should be detected even with leading and/or trailing whitespace
✔ ignoreDirective - should apply to lines lexed during lookahead operations
✔ should be able to ignore a single line with a trailing comment: // jshint:ignore
✔ regression test for GH-1431
✔ jshint ignore:start/end should be detected using single line comments
✔ test destructuring function parameters as es5
✔ test destructuring function parameters as legacy JS
✔ test for parentheses in odd-numbered token
✔ regression crash from GH-1573
✔ make sure we don't throw errors on removed options
✔ 'for of' shouldn't be subject to 'for in' rules
✔ Ignore strings containing braces within array literal declarations
✔ gh-1016: don't issue W088 if identifier is outside of blockscope
✔ testES6UnusedExports
✔ testES6BlockExports
✔ testStrictDirectiveASI
✔ dereferenceDelete
✔ trailingCommaInObjectBindingPattern
✔ trailingCommaInObjectBindingPatternParameters
✔ trailingCommaInArrayBindingPattern
✔ trailingCommaInArrayBindingPatternParameters
✔ testGH1879
✔ commaAfterRestElementInArrayBindingPattern
✔ commaAfterRestElementInArrayBindingPatternParameters
✔ commaAfterRestParameter
✔ extraRestOperator
✔ restOperatorWithoutIdentifier
✔ getAsIdentifierProp
✔ invalidParams
✔ functionKeyword
✔ nonGeneratorAfterGenerator
✔ new.target
✔ lazyIdentifierChecks
✔ parsingCommas
✔ instanceOfLiterals

OK: 1011 assertions (3638ms)

> jshint@2.9.2 test-cli /Users/scottstern/Desktop/JSHINT/jshint
> nodeunit tests/cli.js


cli.js
✔ group - config - normal
✖ group - config - failure

AssertionError: 'xpected token w in JSON at position 0' == 'Error:SyntaxError: Unexpected token w'
    at Object.equal (/Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/lib/types.js:83:39)
    at Object.exports.group.config.failure (/Users/scottstern/Desktop/JSHINT/jshint/tests/cli.js:161:14)
    at /Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/lib/core.js:232:20
    at /Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/deps/async.js:168:13
    at /Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/deps/async.js:131:25
    at /Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/deps/async.js:165:17
    at /Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/deps/async.js:463:34
    at Object.exports.group.config.setUp (/Users/scottstern/Desktop/JSHINT/jshint/tests/cli.js:91:7)
    at /Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/lib/core.js:260:35
    at /Users/scottstern/Desktop/JSHINT/jshint/node_modules/nodeunit/deps/async.js:458:21

✔ group - testPrereq
✔ group - testPrereqCLIOption
✔ group - testPrereqBothConfigAndCLIOption
✔ group - testOverrides
✔ group - testOverridesMatchesRelativePaths
✔ group - testReporter
✔ group - testJSLintReporter
✔ group - testCheckStyleReporter
✔ group - testShowNonErrors
✔ group - testExtensions
✔ group - testMalformedNpmFile
✔ group - testRcFile
✔ group - testHomeRcFile
✔ group - testNoHomeDir
✔ group - testOneLevelRcLookup
✔ group - testTargetRelativeRcLookup
✔ group - testIgnores
✔ group - testMultipleIgnores
✔ group - testExcludePath
✔ group - testAPIIgnores
✔ group - testCollectFiles
✔ group - testGatherOptionalParameters
✔ group - testGather
✔ group - testStatusCode
✔ extract - basic
✔ extract - withIndent
✔ extract - withIndentReportLocation
✔ extract - withIndentReportLocationMultipleFragments
✔ extract - firstLine
✔ extract - sameLine
✔ extract - usingMultipleFiles
✔ extract - \r\n as line terminator (gh-2825)
✔ useStdin - testFilenameOption
✔ useStdin - testFilenameOverridesOption

FAILURES: 1/128 assertions failed (803ms)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "run" "test-cli"
npm ERR! node v6.0.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! jshint@2.9.2 test-cli: `nodeunit tests/cli.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jshint@2.9.2 test-cli script 'nodeunit tests/cli.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jshint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodeunit tests/cli.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jshint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jshint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scottstern/Desktop/JSHINT/jshint/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "run" "test-node"
npm ERR! node v6.0.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! jshint@2.9.2 test-node: `npm run test-unit && npm run test-cli && npm run test-regression`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jshint@2.9.2 test-node script 'npm run test-unit && npm run test-cli && npm run test-regression'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jshint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test-unit && npm run test-cli && npm run test-regression
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jshint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jshint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scottstern/Desktop/JSHINT/jshint/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

Thank you

**Comment by jugglinmike** [comment]
That's a known issue with the test suite in the latest release of Node.js. I've
submitted a fix, but it hasn't found its way into `master` yet--see gh-2945.
Sorry for the confusion there; you can ssafely ignore that error while you work
on your patch.

**Comment by sstern6** [comment]
Perfect thank you just confirming, currently getting familiar with the import block in src/jshint.js line 4500.  Had a question, in linters you specify params via comments you want the linters to follow, ie `// jshint esversion: 6, module: true`.  Jshint must be pulling in this comment somewhere to then aggregate error warnings.  I found where the actually user code was being parsed and how the functions were being called with curr, prev, next.

In this example where I do not seem to understand is where does the program read in the jshint params from the comment, ie `// jshint esversion: 6, module: true`?  The way i am conceptualizing it is, the program sees the `module: true`, then when parsing the code checks that it is wrapped in a module, if not, then add errors to the user output.  Let me know if you need more clarification to my question.

Thank you

**Comment by sstern6** [comment]
Thank you

**Comment by sstern6** [comment]
Thanks @jugglinmike could you please explain some use cases for this error message you would like to see implemented in addition to the one provided? I seem to be confused on semantics.
`error (ImportDeclaration is not allowed outside of a ModuleItem)`

I am not understanding the use case or what other examples would throw this exception in jshint, from what I understand in ES6, a module item is an export statement, ie `export const HELLO = 'hello'` or a function declaration being exported.  In the code sample above you have an import declaration inside of a forced block scope. Why would the example code above throw an error `ImportDeclaration is not allowed outside of a ModuleItem`.  Just trying to gain more context.


Thank you

**Comment by jugglinmike** [comment]
Sure, here you go:

From [the definition of the grammar for "Module"](https://tc39.github.io/ecma262/#sec-modules), you'll see that ImportDeclaration and ExportDeclaration are both classified as "ModuleItem"s. In the ES2015 grammar, a ModuleItem may only appear as a member of a ModuleItemList, and this is distinct from a StatementList. So to your question about my example, [a BlockStatement only supports StatementList](https://tc39.github.io/ecma262/#sec-block).

In more conversation terms, this means that `import` and `export` declarations may only valid at the "top level" of a module. Although this is not technically the global scope in module code, the `isGlobal` method I referenced above should be an acceptable approximation.

What we'll want to do is invoke that function as soon as we begin to lint either module declaration and issue a warning if it returns `false`. Feel free to write the error message in terms that make sense to you; details about "ModuleItemList" are probably too pedantic for our audience. I'll let you know if your message looks good :)

As to your previous question: since it has been deleted, I'm assuming that it's no longer a problem. Please let me know if that's not the case!

**Comment by sstern6** [comment]
Thank you so much for the thorough explanation!  Ill hopefully have some headway completed this weekend!  And yes, previous deleted comments are not relevant any more because I answered my own questions from some deep diving into the code.

**Comment by sstern6** [comment]
@jugglinmike Think I might have the patch ready to submit, would just need to write some tests for it.  Currently, under `stmt("import", function() {` I implemented a condition that writes as follows, 

```
  stmt("import", function() {
    if (!state.funct["(scope)"].block.isGlobal()) {
      error("E061", state.tokens.curr)
    }
```

and in messages.js

`E061: "Import declarations are only allowed at the top level of module scope."`

I didnt add this logic to `stmt("export", function() {` because is the isGlobal function is already being checked on state within the function and invokes an error message if you constrain export within a non global scope.

How does my approach/implementation sound before I test and make a PR?

Thank you

**Comment by sstern6** [comment]
@jugglinmike re your comments about reusing the already built message with parameterizing the message, I am thinking of taking the value and then using that as the parameter for either Import or Export.  Small UI issue I am not sure if it is an issue or not, import and export with not be capitalized pulling from `state.tokens.curr.value`.  I can  build a function for future use of parameter capitalization?  Is the something I should even address?  `line 3, col 5, import declaration must be in global scope.` VS `line 3, col 5, Import declaration must be in global scope.` 

Thanks

**Comment by jugglinmike** [comment]
This might be best to discuss in the context of your pull request, but it seems as though you will have two separate invocations of `error`, so you could specify a distinct literal string value for each--"Import" and "Export".

**Comment by jugglinmike** [comment]
Resolved via gh-2982.
