### ISSUE TITLE
Starting jsdoc comment causes 'Unclosed regular expression' error

### ISSUE THREAD

**Issue by dylansteele8** [jshint/jshint#3004]
When I begin to type `/*` to start a jsdoc comment, I get a jshint error: `E015 - Unclosed regular expression`. Is there a way to turn this error off for jsdoc comments?

**Comment by rwaldron** [comment]
Close the comment: `*/`

**Comment by dylansteele8** [comment]
Sorry, the main issue is with Atom; it throws type errors and other exceptions:
```
Error: /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5309 throw err; ^

TypeError: Cannot read property 'id' of null at Object.x.nud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3228:26) at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:884:34) at /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:2427:23 at Object.x.led (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1151:16) at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:922:36) at Object.fud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:4599:7) at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:881:32) at statement (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1632:9) at statements (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1677:16) at itself (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5288:9)
Error: /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5309
        throw err;
        ^
TypeError: Cannot read property 'id' of null
    at Object.x.nud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3228:26)
    at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:884:34)
    at /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:2427:23
    at Object.x.led (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1151:16)
    at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:922:36)
    at Object.fud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:4599:7)
    at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:881:32)
    at statement (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1632:9)
    at statements (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1677:16)
    at itself (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5288:9)
    at ChildProcess.<anonymous> (/Users/<user>/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by jugglinmike** [comment]
That seems like a different issue than what was originally reported--in this case, JSHint seems to be crashing altogether (not reporting an error). [Our contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md) contain some details about how to make the most helpful bug report. Could you include the information listed there?

**Comment by dharesign** [comment]
Using 2.9.2.  It appears to be an issue when `/*` follows a `{`, e.g.,

    var C = {
      /*
    };

**Comment by dharesign** [comment]
You can see this by pasting the above into the entry at http://jshint.com and checking your browser's console:

> [Error] TypeError: null is not an object (evaluating 'L().id') (jshint.js, line 7)

**Comment by jugglinmike** [comment]
Thanks, @dharesign. That crash was recently addressed (see gh-2937 /
330d429abd861aed767f6c717006d3ae9e90ddc2), so that will be resolved in the next
(post-2.9.2) release of JSHint. Although your stack trace is based on minified
code, by running against the "full" source, I can verify that the offending
expression matches the one identified in the original report.

So I think we have this one licked. Still, I'm going to leave the issue open
for a few days to give @dylansteele8 a chance to verify.

**Comment by dharesign** [comment]
Looks fixed to me with 2.9.3.

**Comment by dharesign** [comment]
Actually, the above code is fixed, but the following code still breaks:

    var C = {
      a: {
        /*
      }
    };

Error:

    TypeError: null is not an object (evaluating 'L().id')

The above code in Atom gives the following stack:

    Error: /Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5386
            throw err;
            ^
    TypeError: Cannot read property 'id' of null
        at Object.x.nud (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3240:26)
        at expression (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34)
        at Object.x.nud (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3303:13)
        at expression (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34)
        at Object.fud (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3678:17)
        at expression (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:885:32)
        at statement (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1636:9)
        at statements (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1681:16)
        at block (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1776:13)
        at doFunction (/Users/daryl/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3068:5)
        at ChildProcess.<anonymous> (/Users/daryl/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:56:20)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:852:16)
        at Socket.<anonymous> (internal/child_process.js:323:11)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at Pipe._handle.close [as _onclose] (net.js:492:12)

**Comment by dharesign** [comment]
I modified the `peek()` function to print out `state.tokens` if `t` is `null`.  It printed:

    state = {
        "prev":{
            "identifier":false,
            "type":"(punctuator)",
            "value":"=",
            "line":1,
            "character":8,
            "from":7
        },
        "next":{
            "identifier":true,
            "type":"(identifier)",
            "value":"s",
            "line":2,
            "character":4,
            "from":3,
            "raw_text":"s"
        },
        "curr":{
            "identifier":false,
            "type":"(punctuator)",
            "value":"{",
            "line":1,
            "character":10,
            "from":9,
            "comment":true
        }
    }

so `state.tokens.next.id` isn't `"(end)"`.

**Comment by dharesign** [comment]
@jugglinmike @dylansteele8 this is still an issue.

**Comment by chimit** [comment]
Have the same problem when typing `/*` after comma.

Atom 1.11.2
linter-jshint 3.0.1

**Comment by jugglinmike** [comment]
@dharesign Thanks for following up on this--I've submitted a patch for that
addresses your latest example: https://github.com/jshint/jshint/pull/3063 . I'm
a bit disappointed that we didn't fully address this the first time around, but
hopefully this new solution is general enough to cover all the edge cases here.

@chimit I'd like to verify that the above patch also fixes your problem, but
we'll need more information first. Can you provide a small example that
requires a comma and causes JSHint version 2.9.4 to crash?

**Comment by chimit** [comment]
It seems like the problem is fixed now.

Atom 1.12.2
linter-jshint 3.0.1

Before it threw an error when I put `/**` before `removeUserGroups` and press Tab.
```
    addUserGroups: function(user_id, groups) {
        this.setUserGroups(user_id, [...new Set(this.getUser(user_id).groups.concat(groups))]);
    },

    removeUserGroups: function(user_id, groups) {
```

**Comment by jugglinmike** [comment]
Thanks for getting back to us, @chimit! I suspect your bug was resolved by gh-2937.
