### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by borisovg** [jshint/jshint#3099]
jshint v2.9.4

test.js:
```
/*jshint*/

var k, o;

for (k in o) {
    if (
}
```

jshint test.js
```
/usr/lib/node_modules/jshint/src/jshint.js:5438
        throw err;
        ^

TypeError: Cannot read property 'type' of undefined
    at Object.fud (/usr/lib/node_modules/jshint/src/jshint.js:3949:15)
    at expression (/usr/lib/node_modules/jshint/src/jshint.js:885:32)
    at statement (/usr/lib/node_modules/jshint/src/jshint.js:1633:9)
    at statements (/usr/lib/node_modules/jshint/src/jshint.js:1678:16)
    at block (/usr/lib/node_modules/jshint/src/jshint.js:1773:13)
    at Object.fud (/usr/lib/node_modules/jshint/src/jshint.js:4311:11)
    at expression (/usr/lib/node_modules/jshint/src/jshint.js:885:32)
    at statement (/usr/lib/node_modules/jshint/src/jshint.js:1633:9)
    at statements (/usr/lib/node_modules/jshint/src/jshint.js:1678:16)
    at itself (/usr/lib/node_modules/jshint/src/jshint.js:5417:9)
```

This is causing error to pop up in Atom editor when I use the [linter-jshint](https://github.com/AtomLinter/linter-jshint) plugin.

Should be similar to #3039.

**Comment by jugglinmike** [comment]
Thanks for the report! This one had me confused for a bit; it turns out you
need to enable the `forin` option to experience the bug. Here's a further
reduced test case:

    /*jshint forin: true*/

    for (x in x) {
      if (
    }

**Comment by jugglinmike** [comment]
A fix is now under review at https://github.com/jshint/jshint/issues/3103

**Comment by Genovo** [comment]
Same error on jshint version 2.9.5
```
$ jshint .
/usr/lib/node_modules/jshint/src/jshint.js:5493
        throw err;
        ^

TypeError: Cannot read property 'type' of undefined
    at Object.fud (/usr/lib/node_modules/jshint/src/jshint.js:4311:24)
    at expression (/usr/lib/node_modules/jshint/src/jshint.js:911:32)
    at statement (/usr/lib/node_modules/jshint/src/jshint.js:1660:9)
    at statements (/usr/lib/node_modules/jshint/src/jshint.js:1705:16)
    at block (/usr/lib/node_modules/jshint/src/jshint.js:1800:13)
    at doFunction (/usr/lib/node_modules/jshint/src/jshint.js:3098:5)
    at Object.fud (/usr/lib/node_modules/jshint/src/jshint.js:3918:5)
    at expression (/usr/lib/node_modules/jshint/src/jshint.js:911:32)
    at statement (/usr/lib/node_modules/jshint/src/jshint.js:1660:9)
    at statements (/usr/lib/node_modules/jshint/src/jshint.js:1705:16)
$ jshint --version
jshint v2.9.5
```
