### ISSUE TITLE
ccap安装编译问题/node@6.2.0/node-gyp v3.5.0/Python 2.7.13

### ISSUE THREAD

**Issue by chiefLit** [jshint/jshint#3105]
```
$ cnpm i ccap
I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
√ Installed 1 packages
√ Linked 3 latest versions

E:\SVN\UED\assets\ak\btjf-blog\node_modules\.0.6.10@ccap>node "C:\Users\lit\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
  hcaptha.cc
  cap.cc
..\addon\cap.cc : warning C4819: ▒▒▒ļ▒▒▒▒▒▒▒▒▒▒ڵ▒ǰ▒▒▒▒ҳ(936)▒б▒ʾ▒▒▒ַ▒▒▒▒뽫▒▒▒ļ▒▒▒▒▒Ϊ Unicode ▒▒ʽ▒Է▒ֹ▒▒▒ݶ▒ʧ [E:\SVN\UED\assets\ak\btjf-blog\node_modules\.0.6.10@ccap\build\hcaptha.vcxproj]
  win_delay_load_hook.cc
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\lit\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lit\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\SVN\UED\assets\ak\btjf-blog\node_modules\.0.6.10@ccap
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\lit\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:77:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npminstall version: 2.24.0
npminstall args: D:\Program Files\nodejs\node.exe C:\Users\lit\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\lit\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org ccap

```

**Comment by jugglinmike** [comment]
The provided output does not reference JSHint in any way, which makes me think the problem is not related to this project. If you believe otherwise, please share a little more context, and we can re-open this issue.
