### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by sossedup** [jshint/jshint#3106]
Everything in my code seems to run smoothly besides this one little error. Has been bugging me for the past week, and was just told to come post here to find a solution. 

Error;

 /node_modules/mysql/lib/protocol/Parser.js:81

throw err;
^
```
TypeError: Cannot read property 'value' of undefined
    at Query._callback (/var/www/html/bot/sell.js:575:23)
    at Query.Sequence.end (/var/www/html/bot/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/var/www/html/bot/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/var/www/html/bot/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/var/www/html/bot/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/var/www/html/bot/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/var/www/html/bot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/html/bot/node_modules/mysql/lib/Connection.js:96:28)

```
Sample of Source Code, (let me know if you need it all):

throw err is on the 7th line.
```

    var hadException = true;
    try {
      this._onPacket(this._packetHeader);
      hadException = false;
    } catch (err) {
      if (!err || typeof err.code !== 'string' || err.code.substr(0, 7) !== 'PARSER_') {
		throw err;
      }
      this._onError(err);
      hadException = false;
    } finally {
      this._advanceToNextPacket();
      if (hadException) {
        process.nextTick(this.write.bind(this));
      }
    }
  }
};
```

**Comment by jugglinmike** [comment]
This appears to be a JavaScript error that is produced as a result of
evaluating the provided code. Is that correct? If so, you may need to raise
this issue elsewhere--JSHint is a tool for statically analyzing JavaScript
source, and it does not execute the input code.

**Comment by jugglinmike** [comment]
It's been a few weeks, so I'm assuming you've worked this out. Let me know if that's not the case, and we can re-open this issue.
