### ISSUE TITLE
Uncaught exception when inspecting a logical asignment

### ISSUE THREAD

**Issue by acarstoiu** [jshint/jshint#3578]
Here is a file submitted to JSHint _2.13.1_:
``` javascript
let a;

a ??= 235;
```
Indeed, _JSHint_ configuration accepts at most `"esversion": 11` and such an assignment is specified in ECMAScript 12 (2021), see [here](https://exploringjs.com/impatient-js/ch_operators.html#logical-assignment-operators). But JSHint crashes with:
```
XYZ\AppData\Roaming\npm\node_modules\jshint\src\jshint.js:6657
        throw err;
        ^

TypeError: Cannot read properties of undefined (reading 'paren')
    at XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\jshint.js:2453:16
    at Object.x.led (XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\jshint.js:1345:16)
    at expression (XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\jshint.js:1007:36)
    at statement (XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\jshint.js:1960:9)
    at statements (XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\jshint.js:2014:16)
    at itself (XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\jshint.js:6635:9)
    at lint (XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\cli.js:495:8)
    at XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\cli.js:665:7
    at Array.forEach (<anonymous>)
    at Object.run (XYZ\AppData\Roaming\npm\node_modules\←[4mjshint←[24m\src\cli.js:651:11)

Node.js v17.0.1
```
If this is regarded as a request to support ES 2021, then so be it.

**Comment by jugglinmike** [comment]
Hi there! JSHint mostly tracks language support at the granularity of individual features rather than revisions of ECMAScript. Since support for logical assignment has already been requested via gh-3544, I'm going to close this issue to keep things organized.
