### ISSUE TITLE
Getting errors while adding as dev-dependancy

### ISSUE THREAD

**Issue by amangtm** [jshint/jshint#3622]
1. jsHint installed globally with no errors
2. `jshint -version` gives output `2.13.5`
3. While adding jshint in project as dev dependancy, gives the following errors -
  **Used command** - `npm install --save-dev jshint`
**Output** - 
```js
> fsevents@1.1.2 install /Users/**/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(403): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@12.16.1 (node-v72 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@12.16.1 (node-v72 ABI) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    sys.exit(gyp.script_main())
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
    return main(sys.argv[1:])
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    return gyp_main(args)
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2214, in GenerateOutput
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2214, in GenerateOutput
    writer.Write(qualified_target, base_path, output_file, spec, configs,
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    writer.Write(qualified_target, base_path, output_file, spec, configs,
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    env = self.GetSortedXcodeEnv()
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1882, in GetSortedXcodeEnv
    env = self.GetSortedXcodeEnv()
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1882, in GetSortedXcodeEnv
    return gyp.xcode_emulation.GetSortedXcodeEnv(
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1615, in GetSortedXcodeEnv
    return gyp.xcode_emulation.GetSortedXcodeEnv(
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1615, in GetSortedXcodeEnv
    env = _GetXcodeEnv(xcode_settings, built_products_dir, srcroot, configuration,
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    env = _GetXcodeEnv(xcode_settings, built_products_dir, srcroot, configuration,
  File "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gypgyp ERR! configure error 
 gypERR!  configure error 
ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! gyp stackERR!     at ChildProcess.onCpExit (/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
 gypSystem  Darwin 21.5.0
ERR! gypstack      at ChildProcess.emit (events.js:311:20)
ERR! gypcommand  "/Users/amangautam/.nvm/versions/node/v12.16.1/bin/node" "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64"
ERR! stackgyp     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
 ERR! cwd /Users/**/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/amangautam/.nvm/versions/node/v12.16.1/bin/node" "/Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64"
gyp ERR! cwd /Users/**/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/amangautam/.nvm/versions/node/v12.16.1/bin/node /Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/**/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 21.5.0
node-pre-gyp ERR! command "/Users/amangautam/.nvm/versions/node/v12.16.1/bin/node" "/Users/**/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/**/node_modules/fsevents
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/Users/amangautam/.nvm/versions/node/v12.16.1/bin/node /Users/amangautam/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/**/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64' (1)
npm WARN @emotion/styled@10.0.27 requires a peer of @emotion/core@^10.0.27 but none is installed. You must install peer dependencies yourself.
npm WARN @emotion/styled-base@10.0.31 requires a peer of @emotion/core@^10.0.28 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/data-grid@4.0.0-alpha.30 requires a peer of react@^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/utils@5.0.0-alpha.35 requires a peer of react@^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack@>=4.43.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0 requires a peer of typescript@>= 3.x but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0 requires a peer of webpack@>= 4 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.2.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN emotion-theming@10.0.27 requires a peer of @emotion/core@^10.0.27 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint@>=6.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-import@>=2.18.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard-jsx@8.1.0 requires a peer of eslint@>=6.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard-jsx@8.1.0 requires a peer of eslint-plugin-react@>=7.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@1.9.0 requires a peer of eslint@>=1.6.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.7.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@5.1.1 requires a peer of eslint@^2.10.2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.1.0 requires a peer of eslint@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@5.1.0 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN final-form-material-ui@0.3.0 requires a peer of @material-ui/core@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN final-form-material-ui@0.3.0 requires a peer of react-final-form@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@4.3.0 requires a peer of webpack@>=4.0.0 < 6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN raw-loader@4.0.2 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-docgen-typescript@2.0.0 requires a peer of typescript@>= 4.3.x but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@4.2.3 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ jshint@2.13.5
updated 1 package and audited 3958 packages in 17.855s

232 packages are looking for funding
  run `npm fund` for details

found 252 vulnerabilities (19 low, 95 moderate, 110 high, 28 critical)
  run `npm audit fix` to fix them, or `npm audit` for details``
```
I am using first time jshint in the project so I am confused whether this is valid errors, pls help
Thanks in advance !!

**Comment by jugglinmike** [comment]
Thanks for taking the time to file a report. Fortunately, there's no problems here!

What that log shows is that [the `fsevents` npm package](https://www.npmjs.com/package/fsevents) is failing to install on your system. I know that sounds bad--it sure *looks* bad. The saving grace comes near the very end:

>     npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
>     npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
>     npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

This means that the failure is tolerable because `fsevents` is an optional dependency. In other words, you can make do without it.

That's also why the final statements in the log sound so positive--they say that the `jshint` package was updated, and they don't mention any error at all.

Another useful signal from the `npm` utility (or any well-behaved command-line utility, really) is the exit status code. This is a convention followed by many, many apps in macOS and GNU/Linux (to name a few), so there are much better places to learn about it then here on the JSHint issue tracker. But in short, when any process ends, it reports a number to the operating system which describes whether it was successful or not. Well-behaved programs report the number `0` to indicate that "everything was okay," and any other number indicates a problem. You can see the exit status of the most recent process by printing a special environment variable named "?".

Here's an example from my terminal:

    $ node -e 'console.log("This process will exit successfully.")'
    This process will exit successfully.
    $ echo $?
    0
    $ node -e 'throw new Error("This program throws an exception, so the process will exit with a non-zero status code.")'
    [eval]:1
    throw new Error("This program throws an exception, so the process will exit with a non-zero status code.")
    ^
    
    Error: This program throws an exception, so the process will exit with a non-zero status code.
        at [eval]:1:7
        at Script.runInThisContext (node:vm:129:12)
        at Object.runInThisContext (node:vm:305:38)
        at node:internal/process/execution:75:19
        at [eval]-wrapper:6:22
        at evalScript (node:internal/process/execution:74:60)
        at node:internal/main/eval_string:27:3
    $ echo $?
    1

This is all to say: if you aren't sure whether `npm` failed to install something, you can try typing `echo $?` to see whether it exited successfully.

Hope that helps!
